apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ot6x015k6-go
  janus-idp.io/tekton: ot6x015k6-go
  backstage.io/kubernetes-id: ot6x015k6-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ot6x015k6-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
